//! Derived color space constants.
//!
//! THIS FILE IS AUTO-GENERATED by gen_colorspace_derived.
//! Do not edit manually. Regenerate with:
//!   cargo run --manifest-path tools/gen_colorspace_derived/Cargo.toml > src/colorspace_derived.rs
//!
//! All constants are computed from primary constants at f64 precision.

// =============================================================================
// D65 ILLUMINANT
// =============================================================================

/// D65 (4-digit) - authoritative for sRGB, BT.709, Display P3, Adobe RGB, Rec.2020.
///
/// Defined by IEC 61966-2-1, ITU-R BT.709-6.
/// xy chromaticity is authoritative; XYZ is derived.
///
/// All D65 color spaces use this exact white point. Using "more accurate" CIE values
/// (0.31272, 0.32903) would produce non-conforming matrices.
pub mod d65 {
    /// Authoritative chromaticity x coordinate
    pub const X: f64 = 0.3127;
    /// Authoritative chromaticity y coordinate
    pub const Y: f64 = 0.329;
    /// Derived XYZ X (from chromaticity)
    pub const XYZ_X: f64 = 0.95045592705167159;
    /// Derived XYZ Y (normalized to 1.0)
    pub const XYZ_Y: f64 = 1.0;
    /// Derived XYZ Z (from chromaticity)
    pub const XYZ_Z: f64 = 1.08905775075987843;
}

// =============================================================================
// D50 ILLUMINANT
// =============================================================================

/// D50 - authoritative for ProPhoto RGB (ISO 22028-2) and ICC PCS (ICC.1:2022-05).
/// XYZ is authoritative; chromaticity is derived.
pub mod d50 {
    /// Authoritative XYZ X
    pub const XYZ_X: f64 = 0.9642;
    /// Authoritative XYZ Y (normalized to 1.0)
    pub const XYZ_Y: f64 = 1.0;
    /// Authoritative XYZ Z
    pub const XYZ_Z: f64 = 0.8249;
    /// Derived chromaticity x
    pub const X: f64 = 0.34570291491879102;
    /// Derived chromaticity y
    pub const Y: f64 = 0.35853859667993260;
}

// =============================================================================
// sRGB / Rec.709 MATRICES
// =============================================================================

/// Linear sRGB → XYZ matrix.
///
/// Derived from authoritative chromaticity primaries (IEC 61966-2-1):
///   Red: (0.640, 0.330), Green: (0.300, 0.600), Blue: (0.150, 0.060)
///   White point D65: (0.3127, 0.3290)
///
/// The 4-decimal matrices in IEC 61966-2-1 are truncated for presentation.
/// Per Amendment 1, higher precision is recommended for N > 8 bit depths.
/// Row-major: result[row] = dot(matrix[row], rgb)
pub const SRGB_TO_XYZ: [[f64; 3]; 3] = [
    [0.41239079926595928, 0.35758433938387801, 0.18048078840183429],
    [0.21263900587151024, 0.71516867876775603, 0.07219231536073371],
    [0.01933081871559182, 0.11919477979462598, 0.95053215224966070],
];

/// XYZ → Linear sRGB matrix (inverse of SRGB_TO_XYZ).
pub const XYZ_TO_SRGB: [[f64; 3]; 3] = [
    [3.24096994190452259, -1.53738317757009391, -0.49861076029300344],
    [-0.96924363628087962, 1.87596750150772040, 0.04155505740717560],
    [0.05563007969699363, -0.20397695888897649, 1.05697151424287838],
];

/// sRGB primaries - authoritative chromaticity coordinates from IEC 61966-2-1.
pub mod srgb_primaries {
    pub const RED_X: f64 = 0.64;
    pub const RED_Y: f64 = 0.33;
    pub const GREEN_X: f64 = 0.3;
    pub const GREEN_Y: f64 = 0.6;
    pub const BLUE_X: f64 = 0.15;
    pub const BLUE_Y: f64 = 0.06;
}

// =============================================================================
// APPLE RGB MATRICES
// =============================================================================

/// Linear Apple RGB → XYZ matrix.
pub const APPLE_RGB_TO_XYZ: [[f64; 3]; 3] = [
    [0.44966162221556277, 0.31625611826990330, 0.18453818656620571],
    [0.24461592248526617, 0.67204425132354439, 0.08333982619118969],
    [0.02518105084407150, 0.14118576708477823, 0.92269093283102854],
];

/// XYZ → Linear Apple RGB matrix.
pub const XYZ_TO_APPLE_RGB: [[f64; 3]; 3] = [
    [2.95197847969455207, -1.28960430406109050, -0.47391530718500535],
    [-1.08508357443367731, 1.99080933911131841, 0.03720167780571314],
    [0.08547221373222354, -0.26942971179950037, 1.09102766940544083],
];

// =============================================================================
// DISPLAY P3 MATRICES
// =============================================================================

/// Linear Display P3 → XYZ matrix.
pub const DISPLAY_P3_TO_XYZ: [[f64; 3]; 3] = [
    [0.48657094864821604, 0.26566769316909306, 0.19821728523436249],
    [0.22897456406974873, 0.69173852183650630, 0.07928691409374500],
    [-0.00000000000000004, 0.04511338185890263, 1.04394436890097597],
];

/// XYZ → Linear Display P3 matrix.
pub const XYZ_TO_DISPLAY_P3: [[f64; 3]; 3] = [
    [2.49349691194142631, -0.93138361791912427, -0.40271078445071695],
    [-0.82948896956157481, 1.76266406031834677, 0.02362468584194360],
    [0.03584583024378447, -0.07617238926804180, 0.95688452400768731],
];

// =============================================================================
// ADOBE RGB MATRICES
// =============================================================================

/// Linear Adobe RGB → XYZ matrix.
pub const ADOBE_RGB_TO_XYZ: [[f64; 3]; 3] = [
    [0.57666904291013055, 0.18555823790654630, 0.18822864623499466],
    [0.29734497525053605, 0.62736356625546608, 0.07529145849399786],
    [0.02703136138641234, 0.07068885253582723, 0.99133753683763859],
];

/// XYZ → Linear Adobe RGB matrix.
pub const XYZ_TO_ADOBE_RGB: [[f64; 3]; 3] = [
    [2.04158790381074695, -0.56500697427885971, -0.34473135077832967],
    [-0.96924363628087984, 1.87596750150772063, 0.04155505740717561],
    [0.01344428063203115, -0.11836239223101841, 1.01517499439120584],
];

// =============================================================================
// PROPHOTO RGB MATRICES (D50 white point)
// =============================================================================

/// Linear ProPhoto RGB → XYZ matrix.
/// Note: Uses D50 white point, not D65.
pub const PROPHOTO_RGB_TO_XYZ: [[f64; 3]; 3] = [
    [0.79766611080389893, 0.13519231336302714, 0.03134157583307381],
    [0.28803704804175084, 0.71187731923739372, 0.00008563272085539],
    [0.0, 0.0, 0.82489999999999986],
];

/// XYZ → Linear ProPhoto RGB matrix.
pub const XYZ_TO_PROPHOTO_RGB: [[f64; 3]; 3] = [
    [1.34595820637406760, -0.25561034000154825, -0.05111233190002151],
    [-0.54459640456991765, 1.50816049166045452, 0.02053504864330213],
    [0.0, 0.0, 1.21226815371560215],
];

// =============================================================================
// REC.2020 MATRICES
// =============================================================================

/// Linear Rec.2020 → XYZ matrix.
pub const REC2020_TO_XYZ: [[f64; 3]; 3] = [
    [0.63695804830129110, 0.14461690358620835, 0.16888097516417208],
    [0.26270021201126698, 0.67799807151887093, 0.05930171646986195],
    [0.00000000000000005, 0.02807269304908743, 1.06098505771079088],
];

/// XYZ → Linear Rec.2020 matrix.
pub const XYZ_TO_REC2020: [[f64; 3]; 3] = [
    [1.71665118797126826, -0.35567078377639255, -0.25336628137365985],
    [-0.66668435183248920, 1.61648123663493926, 0.01576854581391114],
    [0.01763985744531079, -0.04277061325780853, 0.94210312123547391],
];

/// Linear BT.601 625-line (PAL/SECAM) → XYZ matrix.
pub const BT601_625_TO_XYZ: [[f64; 3]; 3] = [
    [0.43055381332990222, 0.34154980353055342, 0.17835231019121597],
    [0.22200430999823084, 0.70665476592528298, 0.07134092407648639],
    [0.02018220999983915, 0.12955337375296855, 0.93932216700707083],
];

/// XYZ → Linear BT.601 625-line (PAL/SECAM) matrix.
pub const XYZ_TO_BT601_625: [[f64; 3]; 3] = [
    [3.06336109008327240, -1.39339017490736783, -0.47582373799753014],
    [-0.96924363628087951, 1.87596750150771996, 0.04155505740717561],
    [0.06786104755356688, -0.22879926962049577, 1.06908961801602787],
];

/// Linear BT.601 525-line (NTSC) → XYZ matrix.
pub const BT601_525_TO_XYZ: [[f64; 3]; 3] = [
    [0.39352090365938974, 0.36525807671760357, 0.19167694667467827],
    [0.21237636070506749, 0.70105985692572292, 0.08656378236920956],
    [0.01873909065044711, 0.11193392673603976, 0.95838473337339136],
];

/// XYZ → Linear BT.601 525-line (NTSC) matrix.
pub const XYZ_TO_BT601_525: [[f64; 3]; 3] = [
    [3.50600328272466299, -1.73979072630283227, -0.54405826836274129],
    [-1.06904755985381494, 1.97777888272878655, 0.03517141933719514],
    [0.05630659173412770, -0.19697565482077187, 1.04995232821873352],
];

/// Original NTSC 1953 (BT.470 M/NTSC) → XYZ matrix.
/// White point: Illuminant C (0.310, 0.316).
/// The Y row gives the original 0.299/0.587/0.114 luma coefficients.
pub const NTSC_1953_TO_XYZ: [[f64; 3]; 3] = [
    [0.60693705115503227, 0.17350884116135754, 0.20026252008082709],
    [0.29893914459874726, 0.58662512964078029, 0.11443572576047262],
    [-0.00000000000000005, 0.06609860615670769, 1.11574832616460795],
];

/// XYZ → Original NTSC 1953 (BT.470 M/NTSC) matrix.
pub const XYZ_TO_NTSC_1953: [[f64; 3]; 3] = [
    [1.90985093071754131, -0.53241368656831711, -0.28818722483973136],
    [-0.98462249428388215, 1.99908203384909400, -0.02830694039510768],
    [0.05833051498847057, -0.11842862134022794, 0.89793641254978696],
];

// =============================================================================
// BRADFORD CHROMATIC ADAPTATION MATRICES
// =============================================================================

// Derived from the Bradford matrix using von Kries adaptation.
// Only needed for D50 ↔ D65 conversion (ProPhoto RGB).
// All D65 color spaces share the same white point, so no adaptation needed between them.

/// Bradford matrix: XYZ → LMS (cone-like response).
/// Primary constant from Lam (1985) and Hunt (1994).
pub const BRADFORD: [[f64; 3]; 3] = [
    [0.8951, 0.2664, -0.1614],
    [-0.7502, 1.7135, 0.0367],
    [0.0389, -0.0685, 1.0296],
];

/// Bradford inverse: LMS → XYZ.
pub const BRADFORD_INV: [[f64; 3]; 3] = [
    [0.98699290546671226, -0.14705425642099013, 0.15996265166373125],
    [0.43230526972339456, 0.51836027153677755, 0.04929122821285560],
    [-0.00852866457517733, 0.04004282165408487, 0.96848669578755020],
];

/// Chromatic adaptation: D50 → D65 (for ProPhoto RGB to D65 spaces).
pub const ADAPT_D50_TO_D65: [[f64; 3]; 3] = [
    [0.95551258892834745, -0.02307297517304352, 0.06330908471330188],
    [-0.02832475931011879, 1.00994292640079575, 0.02105443875138900],
    [0.01232870317482127, -0.02053530765430329, 1.33071368991758909],
];

/// Chromatic adaptation: D65 → D50 (for D65 spaces to ProPhoto RGB).
pub const ADAPT_D65_TO_D50: [[f64; 3]; 3] = [
    [1.04788600322255054, 0.02291876517477952, -0.05021609531173302],
    [0.02958178249800350, 0.99048351849054883, -0.01707870770448270],
    [-0.00925188083920884, 0.01507260748703133, 0.75167813361760361],
];

// =============================================================================
// DIRECT RGB ↔ sRGB MATRICES
// =============================================================================

// These matrices convert directly between linear RGB spaces.
// D65 spaces share the same white point as sRGB, so no chromatic adaptation needed.
// D50 spaces (ProPhoto) include full Bradford D50↔D65 adaptation.

/// Linear Apple RGB → Linear sRGB matrix.
pub const APPLE_RGB_TO_SRGB: [[f64; 3]; 3] = [
    [1.06871585452768825, -0.07860969598003947, 0.00989384145235139],
    [0.02410625513491821, 0.96007092764634328, 0.01582281721873901],
    [0.00173435335705017, 0.02974114446536134, 0.96852450217758823],
];

/// Linear sRGB → Linear Apple RGB matrix.
pub const SRGB_TO_APPLE_RGB: [[f64; 3]; 3] = [
    [0.93398741658423912, 0.07680843758720021, -0.01079585417143902],
    [-0.02343562489314104, 1.04018983738463011, -0.01675421249148942],
    [-0.00095285344225948, -0.03207936312068568, 1.03303221656294553],
];

/// Linear Display P3 → Linear sRGB matrix.
pub const DISPLAY_P3_TO_SRGB: [[f64; 3]; 3] = [
    [1.22494017628055984, -0.22494017628055996, -0.00000000000000011],
    [-0.04205695470968812, 1.04205695470968829, 0.00000000000000002],
    [-0.01963755459033444, -0.07863604555063181, 1.09827360014096631],
];

/// Linear sRGB → Linear Display P3 matrix.
pub const SRGB_TO_DISPLAY_P3: [[f64; 3]; 3] = [
    [0.82246196871436239, 0.17753803128563794, 0.00000000000000011],
    [0.03319419885096169, 0.96680580114903847, 0.00000000000000002],
    [0.01708263072112004, 0.07239744066396342, 0.91051992861491660],
];

/// Linear Adobe RGB → Linear sRGB matrix.
pub const ADOBE_RGB_TO_SRGB: [[f64; 3]; 3] = [
    [1.39835574396077855, -0.39835574396077855, 0.0],
    [-0.00000000000000003, 1.0, -0.00000000000000001],
    [-0.00000000000000000, -0.04292898929447317, 1.04292898929447286],
];

/// Linear sRGB → Linear Adobe RGB matrix.
pub const SRGB_TO_ADOBE_RGB: [[f64; 3]; 3] = [
    [0.71512560685562465, 0.28487439314437574, 0.0],
    [-0.00000000000000005, 1.00000000000000022, -0.00000000000000002],
    [0.00000000000000001, 0.04116194845011842, 0.95883805154988200],
];

/// Linear Rec.2020 → Linear sRGB matrix.
pub const REC2020_TO_SRGB: [[f64; 3]; 3] = [
    [1.66049100210843470, -0.58764113878854962, -0.07284986331988486],
    [-0.12455047452159052, 1.13289989712596006, -0.00834942260436949],
    [-0.01815076335490522, -0.10057889800800737, 1.11872966136291252],
];

/// Linear sRGB → Linear Rec.2020 matrix.
pub const SRGB_TO_REC2020: [[f64; 3]; 3] = [
    [0.62740389593469903, 0.32928303837788375, 0.04331306568741727],
    [0.06909728935823199, 0.91954039507545904, 0.01136231556630915],
    [0.01639143887515023, 0.08801330787722578, 0.89559525324762401],
];

/// Linear ProPhoto RGB → Linear sRGB matrix (includes D50→D65 adaptation).
pub const PROPHOTO_RGB_TO_SRGB: [[f64; 3]; 3] = [
    [2.03421815307886034, -0.72753647328635762, -0.30668167979250266],
    [-0.22879805605430628, 1.23173028211912650, -0.00293222606482029],
    [-0.00855553292091616, -0.15328657487737771, 1.16184210779829367],
];

/// Linear sRGB → Linear ProPhoto RGB matrix (includes D65→D50 adaptation).
pub const SRGB_TO_PROPHOTO_RGB: [[f64; 3]; 3] = [
    [0.52931245871495103, 0.33013619885653112, 0.14055134242851772],
    [0.09836174743191933, 0.87347008972219387, 0.02816816284588725],
    [0.01687499996529928, 0.11767152224163420, 0.86545347779306703],
];

// =============================================================================
// CIELAB DERIVED CONSTANTS
// =============================================================================

/// CIELAB constants derived from δ = 6/29.
pub mod cielab {
    /// δ = 6/29
    pub const DELTA: f64 = 0.20689655172413793;

    /// ε = δ³ = (6/29)³ ≈ 0.008856
    /// Threshold for f(t): if t > EPSILON, use cube root.
    pub const EPSILON: f64 = 0.00885645167903563;

    /// κ = (29/6)² / 3 ≈ 7.787
    /// Linear segment slope: f(t) = κ*t + 16/116 for t ≤ ε
    pub const KAPPA: f64 = 7.78703703703703631;

    /// Linear segment offset = 16/116 = 4/29
    pub const OFFSET: f64 = 0.13793103448275862;

    /// Threshold in f-space for inverse: f(ε) = δ = 6/29
    /// If f > F_THRESHOLD, use cube; otherwise use linear inverse.
    pub const F_THRESHOLD: f64 = 0.20689655172413793;
}

// =============================================================================
// TRANSFER FUNCTION DERIVED CONSTANTS
// =============================================================================

/// sRGB decode threshold in encoded space.
/// sRGB specification threshold (0.0031308) * linear_slope (12.92)
pub const SRGB_DECODE_THRESHOLD: f64 = 0.040449936;

/// Adobe RGB gamma: 563/256
pub const ADOBE_RGB_GAMMA: f64 = 2.19921875;

/// ProPhoto RGB linear segment threshold: 1/512
pub const PROPHOTO_THRESHOLD: f64 = 0.001953125;

/// ProPhoto RGB decode threshold in encoded space: 16 * (1/512)
pub const PROPHOTO_DECODE_THRESHOLD: f64 = 0.03125;

// =============================================================================
// Y'CbCr BT.709 DERIVED CONSTANTS
// =============================================================================

/// Cb channel scaling factor: 2(1-Kb)
pub const YCBCR_CB_SCALE: f64 = 1.85561536927853266;

/// Cr channel scaling factor: 2(1-Kr)
pub const YCBCR_CR_SCALE: f64 = 1.57472198825697962;

/// RGB' → Y'CbCr matrix (BT.709).
/// Y' = Kr*R' + Kg*G' + Kb*B'
/// Cb = 0.5*(B'-Y')/(1-Kb)
/// Cr = 0.5*(R'-Y')/(1-Kr)
pub const RGB_TO_YCBCR: [[f64; 3]; 3] = [
    [0.21263900587151024, 0.71516867876775603, 0.07219231536073371],
    [-0.11459217755573169, -0.38540782244426830, 0.5],
    [0.5, -0.45415551703787305, -0.04584448296212691],
];

/// Y'CbCr → RGB' matrix (BT.709).
pub const YCBCR_TO_RGB: [[f64; 3]; 3] = [
    [1.0, 0.0, 1.57472198825697962],
    [1.0, -0.18731408953478898, -0.46820747055634204],
    [1.0, 1.85561536927853266, 0.0],
];

// =============================================================================
// f32 VERSIONS FOR RUNTIME USE
// =============================================================================

/// f32 module for runtime use. All values derived from f64 constants.
pub mod f32 {

    // -------------------------------------------------------------------------
    // ILLUMINANT XYZ
    // -------------------------------------------------------------------------

    /// D65 XYZ (computed from f32 sRGB matrix row sums for internal consistency)
    pub const D65_X: f32 = 0.9504559;
    pub const D65_Y: f32 = 1.0;
    pub const D65_Z: f32 = 1.0890577;
    pub const D65_XYZ: [f32; 3] = [D65_X, D65_Y, D65_Z];

    /// D50 XYZ (authoritative for ICC/ProPhoto)
    pub const D50_X: f32 = 0.9642 as f32;
    pub const D50_Y: f32 = 1.0 as f32;
    pub const D50_Z: f32 = 0.8249 as f32;
    pub const D50_XYZ: [f32; 3] = [D50_X, D50_Y, D50_Z];

    // -------------------------------------------------------------------------
    // ILLUMINANT CHROMATICITY
    // -------------------------------------------------------------------------

    /// D65 chromaticity (authoritative for display standards)
    pub const D65_CHROMATICITY: [f32; 2] = [0.3127 as f32, 0.329 as f32];
    /// D50 chromaticity (derived from authoritative XYZ)
    pub const D50_CHROMATICITY: [f32; 2] = [0.34570291491879102 as f32, 0.35853859667993260 as f32];

    // -------------------------------------------------------------------------
    // RGB <-> XYZ MATRICES
    // -------------------------------------------------------------------------

    pub const SRGB_TO_XYZ: [[f32; 3]; 3] = [
        [0.41239079926595928 as f32, 0.35758433938387801 as f32, 0.18048078840183429 as f32],
        [0.21263900587151024 as f32, 0.71516867876775603 as f32, 0.07219231536073371 as f32],
        [0.01933081871559182 as f32, 0.11919477979462598 as f32, 0.95053215224966070 as f32],
    ];
    pub const XYZ_TO_SRGB: [[f32; 3]; 3] = [
        [3.24096994190452259 as f32, -1.53738317757009391 as f32, -0.49861076029300344 as f32],
        [-0.96924363628087962 as f32, 1.87596750150772040 as f32, 0.04155505740717560 as f32],
        [0.05563007969699363 as f32, -0.20397695888897649 as f32, 1.05697151424287838 as f32],
    ];

    /// sRGB primaries (authoritative chromaticity coordinates)
    pub const SRGB_RED_XY: [f32; 2] = [0.64 as f32, 0.33 as f32];
    pub const SRGB_GREEN_XY: [f32; 2] = [0.3 as f32, 0.6 as f32];
    pub const SRGB_BLUE_XY: [f32; 2] = [0.15 as f32, 0.06 as f32];

    pub const APPLE_RGB_TO_XYZ: [[f32; 3]; 3] = [
        [0.44966162221556277 as f32, 0.31625611826990330 as f32, 0.18453818656620571 as f32],
        [0.24461592248526617 as f32, 0.67204425132354439 as f32, 0.08333982619118969 as f32],
        [0.02518105084407150 as f32, 0.14118576708477823 as f32, 0.92269093283102854 as f32],
    ];
    pub const XYZ_TO_APPLE_RGB: [[f32; 3]; 3] = [
        [2.95197847969455207 as f32, -1.28960430406109050 as f32, -0.47391530718500535 as f32],
        [-1.08508357443367731 as f32, 1.99080933911131841 as f32, 0.03720167780571314 as f32],
        [0.08547221373222354 as f32, -0.26942971179950037 as f32, 1.09102766940544083 as f32],
    ];

    pub const DISPLAY_P3_TO_XYZ: [[f32; 3]; 3] = [
        [0.48657094864821604 as f32, 0.26566769316909306 as f32, 0.19821728523436249 as f32],
        [0.22897456406974873 as f32, 0.69173852183650630 as f32, 0.07928691409374500 as f32],
        [-0.00000000000000004 as f32, 0.04511338185890263 as f32, 1.04394436890097597 as f32],
    ];
    pub const XYZ_TO_DISPLAY_P3: [[f32; 3]; 3] = [
        [2.49349691194142631 as f32, -0.93138361791912427 as f32, -0.40271078445071695 as f32],
        [-0.82948896956157481 as f32, 1.76266406031834677 as f32, 0.02362468584194360 as f32],
        [0.03584583024378447 as f32, -0.07617238926804180 as f32, 0.95688452400768731 as f32],
    ];

    pub const ADOBE_RGB_TO_XYZ: [[f32; 3]; 3] = [
        [0.57666904291013055 as f32, 0.18555823790654630 as f32, 0.18822864623499466 as f32],
        [0.29734497525053605 as f32, 0.62736356625546608 as f32, 0.07529145849399786 as f32],
        [0.02703136138641234 as f32, 0.07068885253582723 as f32, 0.99133753683763859 as f32],
    ];
    pub const XYZ_TO_ADOBE_RGB: [[f32; 3]; 3] = [
        [2.04158790381074695 as f32, -0.56500697427885971 as f32, -0.34473135077832967 as f32],
        [-0.96924363628087984 as f32, 1.87596750150772063 as f32, 0.04155505740717561 as f32],
        [0.01344428063203115 as f32, -0.11836239223101841 as f32, 1.01517499439120584 as f32],
    ];

    pub const PROPHOTO_RGB_TO_XYZ: [[f32; 3]; 3] = [
        [0.79766611080389893 as f32, 0.13519231336302714 as f32, 0.03134157583307381 as f32],
        [0.28803704804175084 as f32, 0.71187731923739372 as f32, 0.00008563272085539 as f32],
        [0.0 as f32, 0.0 as f32, 0.82489999999999986 as f32],
    ];
    pub const XYZ_TO_PROPHOTO_RGB: [[f32; 3]; 3] = [
        [1.34595820637406760 as f32, -0.25561034000154825 as f32, -0.05111233190002151 as f32],
        [-0.54459640456991765 as f32, 1.50816049166045452 as f32, 0.02053504864330213 as f32],
        [0.0 as f32, 0.0 as f32, 1.21226815371560215 as f32],
    ];

    pub const REC2020_TO_XYZ: [[f32; 3]; 3] = [
        [0.63695804830129110 as f32, 0.14461690358620835 as f32, 0.16888097516417208 as f32],
        [0.26270021201126698 as f32, 0.67799807151887093 as f32, 0.05930171646986195 as f32],
        [0.00000000000000005 as f32, 0.02807269304908743 as f32, 1.06098505771079088 as f32],
    ];
    pub const XYZ_TO_REC2020: [[f32; 3]; 3] = [
        [1.71665118797126826 as f32, -0.35567078377639255 as f32, -0.25336628137365985 as f32],
        [-0.66668435183248920 as f32, 1.61648123663493926 as f32, 0.01576854581391114 as f32],
        [0.01763985744531079 as f32, -0.04277061325780853 as f32, 0.94210312123547391 as f32],
    ];

    pub const BT601_625_TO_XYZ: [[f32; 3]; 3] = [
        [0.43055381332990222 as f32, 0.34154980353055342 as f32, 0.17835231019121597 as f32],
        [0.22200430999823084 as f32, 0.70665476592528298 as f32, 0.07134092407648639 as f32],
        [0.02018220999983915 as f32, 0.12955337375296855 as f32, 0.93932216700707083 as f32],
    ];
    pub const XYZ_TO_BT601_625: [[f32; 3]; 3] = [
        [3.06336109008327240 as f32, -1.39339017490736783 as f32, -0.47582373799753014 as f32],
        [-0.96924363628087951 as f32, 1.87596750150771996 as f32, 0.04155505740717561 as f32],
        [0.06786104755356688 as f32, -0.22879926962049577 as f32, 1.06908961801602787 as f32],
    ];

    pub const BT601_525_TO_XYZ: [[f32; 3]; 3] = [
        [0.39352090365938974 as f32, 0.36525807671760357 as f32, 0.19167694667467827 as f32],
        [0.21237636070506749 as f32, 0.70105985692572292 as f32, 0.08656378236920956 as f32],
        [0.01873909065044711 as f32, 0.11193392673603976 as f32, 0.95838473337339136 as f32],
    ];
    pub const XYZ_TO_BT601_525: [[f32; 3]; 3] = [
        [3.50600328272466299 as f32, -1.73979072630283227 as f32, -0.54405826836274129 as f32],
        [-1.06904755985381494 as f32, 1.97777888272878655 as f32, 0.03517141933719514 as f32],
        [0.05630659173412770 as f32, -0.19697565482077187 as f32, 1.04995232821873352 as f32],
    ];

    pub const NTSC_1953_TO_XYZ: [[f32; 3]; 3] = [
        [0.60693705115503227 as f32, 0.17350884116135754 as f32, 0.20026252008082709 as f32],
        [0.29893914459874726 as f32, 0.58662512964078029 as f32, 0.11443572576047262 as f32],
        [-0.00000000000000005 as f32, 0.06609860615670769 as f32, 1.11574832616460795 as f32],
    ];
    pub const XYZ_TO_NTSC_1953: [[f32; 3]; 3] = [
        [1.90985093071754131 as f32, -0.53241368656831711 as f32, -0.28818722483973136 as f32],
        [-0.98462249428388215 as f32, 1.99908203384909400 as f32, -0.02830694039510768 as f32],
        [0.05833051498847057 as f32, -0.11842862134022794 as f32, 0.89793641254978696 as f32],
    ];

    // -------------------------------------------------------------------------
    // CHROMATIC ADAPTATION MATRICES
    // -------------------------------------------------------------------------

    pub const BRADFORD: [[f32; 3]; 3] = [
        [0.8951 as f32, 0.2664 as f32, -0.1614 as f32],
        [-0.7502 as f32, 1.7135 as f32, 0.0367 as f32],
        [0.0389 as f32, -0.0685 as f32, 1.0296 as f32],
    ];
    pub const BRADFORD_INV: [[f32; 3]; 3] = [
        [0.98699290546671226 as f32, -0.14705425642099013 as f32, 0.15996265166373125 as f32],
        [0.43230526972339456 as f32, 0.51836027153677755 as f32, 0.04929122821285560 as f32],
        [-0.00852866457517733 as f32, 0.04004282165408487 as f32, 0.96848669578755020 as f32],
    ];

    pub const ADAPT_D50_TO_D65: [[f32; 3]; 3] = [
        [0.95551258892834745 as f32, -0.02307297517304352 as f32, 0.06330908471330188 as f32],
        [-0.02832475931011879 as f32, 1.00994292640079575 as f32, 0.02105443875138900 as f32],
        [0.01232870317482127 as f32, -0.02053530765430329 as f32, 1.33071368991758909 as f32],
    ];
    pub const ADAPT_D65_TO_D50: [[f32; 3]; 3] = [
        [1.04788600322255054 as f32, 0.02291876517477952 as f32, -0.05021609531173302 as f32],
        [0.02958178249800350 as f32, 0.99048351849054883 as f32, -0.01707870770448270 as f32],
        [-0.00925188083920884 as f32, 0.01507260748703133 as f32, 0.75167813361760361 as f32],
    ];

    // -------------------------------------------------------------------------
    // DIRECT RGB <-> sRGB MATRICES
    // -------------------------------------------------------------------------

    pub const APPLE_RGB_TO_SRGB: [[f32; 3]; 3] = [
        [1.06871585452768825 as f32, -0.07860969598003947 as f32, 0.00989384145235139 as f32],
        [0.02410625513491821 as f32, 0.96007092764634328 as f32, 0.01582281721873901 as f32],
        [0.00173435335705017 as f32, 0.02974114446536134 as f32, 0.96852450217758823 as f32],
    ];
    pub const SRGB_TO_APPLE_RGB: [[f32; 3]; 3] = [
        [0.93398741658423912 as f32, 0.07680843758720021 as f32, -0.01079585417143902 as f32],
        [-0.02343562489314104 as f32, 1.04018983738463011 as f32, -0.01675421249148942 as f32],
        [-0.00095285344225948 as f32, -0.03207936312068568 as f32, 1.03303221656294553 as f32],
    ];

    pub const DISPLAY_P3_TO_SRGB: [[f32; 3]; 3] = [
        [1.22494017628055984 as f32, -0.22494017628055996 as f32, -0.00000000000000011 as f32],
        [-0.04205695470968812 as f32, 1.04205695470968829 as f32, 0.00000000000000002 as f32],
        [-0.01963755459033444 as f32, -0.07863604555063181 as f32, 1.09827360014096631 as f32],
    ];
    pub const SRGB_TO_DISPLAY_P3: [[f32; 3]; 3] = [
        [0.82246196871436239 as f32, 0.17753803128563794 as f32, 0.00000000000000011 as f32],
        [0.03319419885096169 as f32, 0.96680580114903847 as f32, 0.00000000000000002 as f32],
        [0.01708263072112004 as f32, 0.07239744066396342 as f32, 0.91051992861491660 as f32],
    ];

    pub const ADOBE_RGB_TO_SRGB: [[f32; 3]; 3] = [
        [1.39835574396077855 as f32, -0.39835574396077855 as f32, 0.0 as f32],
        [-0.00000000000000003 as f32, 1.0 as f32, -0.00000000000000001 as f32],
        [-0.00000000000000000 as f32, -0.04292898929447317 as f32, 1.04292898929447286 as f32],
    ];
    pub const SRGB_TO_ADOBE_RGB: [[f32; 3]; 3] = [
        [0.71512560685562465 as f32, 0.28487439314437574 as f32, 0.0 as f32],
        [-0.00000000000000005 as f32, 1.00000000000000022 as f32, -0.00000000000000002 as f32],
        [0.00000000000000001 as f32, 0.04116194845011842 as f32, 0.95883805154988200 as f32],
    ];

    pub const REC2020_TO_SRGB: [[f32; 3]; 3] = [
        [1.66049100210843470 as f32, -0.58764113878854962 as f32, -0.07284986331988486 as f32],
        [-0.12455047452159052 as f32, 1.13289989712596006 as f32, -0.00834942260436949 as f32],
        [-0.01815076335490522 as f32, -0.10057889800800737 as f32, 1.11872966136291252 as f32],
    ];
    pub const SRGB_TO_REC2020: [[f32; 3]; 3] = [
        [0.62740389593469903 as f32, 0.32928303837788375 as f32, 0.04331306568741727 as f32],
        [0.06909728935823199 as f32, 0.91954039507545904 as f32, 0.01136231556630915 as f32],
        [0.01639143887515023 as f32, 0.08801330787722578 as f32, 0.89559525324762401 as f32],
    ];

    pub const PROPHOTO_RGB_TO_SRGB: [[f32; 3]; 3] = [
        [2.03421815307886034 as f32, -0.72753647328635762 as f32, -0.30668167979250266 as f32],
        [-0.22879805605430628 as f32, 1.23173028211912650 as f32, -0.00293222606482029 as f32],
        [-0.00855553292091616 as f32, -0.15328657487737771 as f32, 1.16184210779829367 as f32],
    ];
    pub const SRGB_TO_PROPHOTO_RGB: [[f32; 3]; 3] = [
        [0.52931245871495103 as f32, 0.33013619885653112 as f32, 0.14055134242851772 as f32],
        [0.09836174743191933 as f32, 0.87347008972219387 as f32, 0.02816816284588725 as f32],
        [0.01687499996529928 as f32, 0.11767152224163420 as f32, 0.86545347779306703 as f32],
    ];

    // -------------------------------------------------------------------------
    // TRANSFER FUNCTION CONSTANTS
    // -------------------------------------------------------------------------

    /// sRGB encode threshold (linear space)
    pub const SRGB_THRESHOLD: f32 = 0.0031308 as f32;
    /// sRGB decode threshold (encoded space)
    pub const SRGB_DECODE_THRESHOLD: f32 = 0.040449936 as f32;
    pub const SRGB_LINEAR_SLOPE: f32 = 12.92 as f32;
    pub const SRGB_GAMMA: f32 = 2.4;
    pub const SRGB_SCALE: f32 = 1.055;
    pub const SRGB_OFFSET: f32 = 0.055;

    pub const ADOBE_RGB_GAMMA: f32 = 2.19921875 as f32;
    pub const APPLE_RGB_GAMMA: f32 = 1.8 as f32;

    pub const PROPHOTO_THRESHOLD: f32 = 0.001953125 as f32;
    pub const PROPHOTO_DECODE_THRESHOLD: f32 = 0.03125 as f32;
    pub const PROPHOTO_LINEAR_MULTIPLIER: f32 = 16.0 as f32;
    pub const PROPHOTO_GAMMA: f32 = 1.8 as f32;

    pub const GAMMA_22: f32 = 2.2;

    // -------------------------------------------------------------------------
    // CIELAB CONSTANTS
    // -------------------------------------------------------------------------

    pub const CIELAB_DELTA: f32 = 0.20689655172413793 as f32;
    pub const CIELAB_EPSILON: f32 = 0.00885645167903563 as f32;
    pub const CIELAB_KAPPA: f32 = 7.78703703703703631 as f32;
    pub const CIELAB_OFFSET: f32 = 0.13793103448275862 as f32;
    pub const CIELAB_F_THRESHOLD: f32 = 0.20689655172413793 as f32;
    /// Negative threshold: where linear segment meets cbrt for t < 0
    pub const CIELAB_NEG_EPSILON: f32 = 0.07085161343228505 as f32;
    /// f(-NEG_EPSILON) threshold in f-space for inverse
    pub const CIELAB_NEG_F_THRESHOLD: f32 = -0.41379310344827586 as f32;
    pub const CIELAB_L_SCALE: f32 = 116.0;
    pub const CIELAB_L_OFFSET: f32 = 16.0;
    pub const CIELAB_A_SCALE: f32 = 500.0;
    pub const CIELAB_B_SCALE: f32 = 200.0;

    // -------------------------------------------------------------------------
    // CIE94 COLOR DIFFERENCE CONSTANTS
    // -------------------------------------------------------------------------

    /// CIE94 K1 coefficient for SC = 1 + K1*C
    pub const CIE94_K1: f32 = 0.045 as f32;
    /// CIE94 K2 coefficient for SH = 1 + K2*C
    pub const CIE94_K2: f32 = 0.015 as f32;

    // -------------------------------------------------------------------------
    // CIEDE2000 COLOR DIFFERENCE CONSTANTS
    // -------------------------------------------------------------------------

    /// 25^7 - chroma correction threshold (exact integer)
    pub const CIEDE2000_POW25_7: f32 = 6103515625.0 as f32;
    /// T factor: 30° in radians (derived: π/6)
    pub const CIEDE2000_T_30_RAD: f32 = 0.52359877559829882 as f32;
    /// T factor: 6° in radians (derived: π/30)
    pub const CIEDE2000_T_6_RAD: f32 = 0.10471975511965977 as f32;
    /// T factor: 63° in radians (derived: 7π/20)
    pub const CIEDE2000_T_63_RAD: f32 = 1.09955742875642759 as f32;
    /// RT term: 275° in radians (derived: 55π/36)
    pub const CIEDE2000_RT_275_RAD: f32 = 4.79965544298440605 as f32;
    /// RT term: 25° in radians (derived: 5π/36)
    pub const CIEDE2000_RT_25_RAD: f32 = 0.43633231299858238 as f32;
    /// RT term: 30° for Δθ in radians (derived: π/6)
    pub const CIEDE2000_RT_30_RAD: f32 = 0.52359877559829882 as f32;
    /// SL weighting function: L* midpoint (primary)
    pub const CIEDE2000_SL_L_MIDPOINT: f32 = 50.0 as f32;
    /// SL weighting function: denominator offset (primary)
    pub const CIEDE2000_SL_DENOM_OFFSET: f32 = 20.0 as f32;

    // -------------------------------------------------------------------------
    // OKLAB MATRICES (from primary constants)
    // -------------------------------------------------------------------------

    /// OKLab M1: Linear sRGB → LMS
    pub const OKLAB_M1: [[f32; 3]; 3] = [
        [0.4122214708 as f32, 0.5363325363 as f32, 0.0514459929 as f32],
        [0.2119034982 as f32, 0.6806995451 as f32, 0.1073969566 as f32],
        [0.0883024619 as f32, 0.2817188376 as f32, 0.6299787005 as f32],
    ];

    /// OKLab M2: LMS' → Lab
    pub const OKLAB_M2: [[f32; 3]; 3] = [
        [0.2104542553 as f32, 0.793617785 as f32, -0.0040720468 as f32],
        [1.9779984951 as f32, -2.428592205 as f32, 0.4505937099 as f32],
        [0.0259040371 as f32, 0.7827717662 as f32, -0.808675766 as f32],
    ];

    /// OKLab M1_inv: LMS → Linear sRGB
    pub const OKLAB_M1_INV: [[f32; 3]; 3] = [
        [4.0767416621 as f32, -3.3077115913 as f32, 0.2309699292 as f32],
        [-1.2684380046 as f32, 2.6097574011 as f32, -0.3413193965 as f32],
        [-0.0041960863 as f32, -0.7034186147 as f32, 1.707614701 as f32],
    ];

    /// OKLab M2_inv: Lab → LMS'
    pub const OKLAB_M2_INV: [[f32; 3]; 3] = [
        [1.0 as f32, 0.3963377774 as f32, 0.2158037573 as f32],
        [1.0 as f32, -0.1055613458 as f32, -0.0638541728 as f32],
        [1.0 as f32, -0.0894841775 as f32, -1.291485548 as f32],
    ];

    // -------------------------------------------------------------------------
    // Y'CbCr CONSTANTS
    // -------------------------------------------------------------------------

    /// BT.709 luma coefficients (derived from sRGB matrix)
    pub const YCBCR_KR: f32 = 0.21263900587151024 as f32;
    pub const YCBCR_KG: f32 = 0.71516867876775603 as f32;
    pub const YCBCR_KB: f32 = 0.07219231536073371 as f32;
    pub const YCBCR_CB_SCALE: f32 = 1.85561536927853266 as f32;
    pub const YCBCR_CR_SCALE: f32 = 1.57472198825697962 as f32;

    pub const RGB_TO_YCBCR: [[f32; 3]; 3] = [
        [0.21263900587151024 as f32, 0.71516867876775603 as f32, 0.07219231536073371 as f32],
        [-0.11459217755573169 as f32, -0.38540782244426830 as f32, 0.5 as f32],
        [0.5 as f32, -0.45415551703787305 as f32, -0.04584448296212691 as f32],
    ];
    pub const YCBCR_TO_RGB: [[f32; 3]; 3] = [
        [1.0 as f32, 0.0 as f32, 1.57472198825697962 as f32],
        [1.0 as f32, -0.18731408953478898 as f32, -0.46820747055634204 as f32],
        [1.0 as f32, 1.85561536927853266 as f32, 0.0 as f32],
    ];

    /// BT.601 625-line (PAL/SECAM) true luminance coefficients
    /// Derived from RGB→XYZ matrix. NOT the legacy 0.299/0.587/0.114 values.
    pub const BT601_625_KR: f32 = 0.22200430999823084 as f32;
    pub const BT601_625_KG: f32 = 0.70665476592528298 as f32;
    pub const BT601_625_KB: f32 = 0.07134092407648639 as f32;

    /// BT.601 525-line (NTSC) true luminance coefficients
    /// Derived from RGB→XYZ matrix. NOT the legacy 0.299/0.587/0.114 values.
    pub const BT601_525_KR: f32 = 0.21237636070506749 as f32;
    pub const BT601_525_KG: f32 = 0.70105985692572292 as f32;
    pub const BT601_525_KB: f32 = 0.08656378236920956 as f32;

    /// Original NTSC 1953 (BT.470 M/NTSC) luminance coefficients
    /// Derived from RGB→XYZ matrix with Illuminant C white point.
    /// These are the TRUE source of 0.299/0.587/0.114 (which rounds to these).
    pub const NTSC_1953_KR: f32 = 0.29893914459874726 as f32;
    pub const NTSC_1953_KG: f32 = 0.58662512964078029 as f32;
    pub const NTSC_1953_KB: f32 = 0.11443572576047262 as f32;

    /// Legacy Y'CbCr coefficients (rounded from NTSC 1953)
    /// From BT.470 M/NTSC with Illuminant C. Used in BT.601 Y'CbCr for compatibility.
    /// Note: These do NOT match true luminance for modern D65 color spaces.
    pub const YCBCR_LEGACY_KR: f32 = 0.299;
    pub const YCBCR_LEGACY_KG: f32 = 0.587;
    pub const YCBCR_LEGACY_KB: f32 = 0.114;

    // -------------------------------------------------------------------------
    // BIT DEPTH
    // -------------------------------------------------------------------------

    pub const UINT8_MAX: f32 = 255.0;
    pub const UINT16_MAX: f32 = 65535.0;
}

// =============================================================================
// TESTS
// =============================================================================

#[cfg(test)]
mod tests {
    use super::*;

    fn mat_mul(a: [[f64; 3]; 3], b: [[f64; 3]; 3]) -> [[f64; 3]; 3] {
        let mut r = [[0.0; 3]; 3];
        for i in 0..3 {
            for j in 0..3 {
                for k in 0..3 {
                    r[i][j] += a[i][k] * b[k][j];
                }
            }
        }
        r
    }

    fn is_identity(m: [[f64; 3]; 3], tol: f64) -> bool {
        for i in 0..3 {
            for j in 0..3 {
                let expected = if i == j { 1.0 } else { 0.0 };
                if (m[i][j] - expected).abs() > tol {
                    return false;
                }
            }
        }
        true
    }

    #[test]
    fn test_srgb_matrices_are_inverses() {
        let product = mat_mul(SRGB_TO_XYZ, XYZ_TO_SRGB);
        assert!(is_identity(product, 1e-10), "SRGB matrices not inverse");
    }

    #[test]
    fn test_apple_matrices_are_inverses() {
        let product = mat_mul(APPLE_RGB_TO_XYZ, XYZ_TO_APPLE_RGB);
        assert!(is_identity(product, 1e-10), "Apple RGB matrices not inverse");
    }

    #[test]
    fn test_p3_matrices_are_inverses() {
        let product = mat_mul(DISPLAY_P3_TO_XYZ, XYZ_TO_DISPLAY_P3);
        assert!(is_identity(product, 1e-10), "Display P3 matrices not inverse");
    }

    #[test]
    fn test_adobe_matrices_are_inverses() {
        let product = mat_mul(ADOBE_RGB_TO_XYZ, XYZ_TO_ADOBE_RGB);
        assert!(is_identity(product, 1e-10), "Adobe RGB matrices not inverse");
    }

    #[test]
    fn test_prophoto_matrices_are_inverses() {
        let product = mat_mul(PROPHOTO_RGB_TO_XYZ, XYZ_TO_PROPHOTO_RGB);
        assert!(is_identity(product, 1e-10), "ProPhoto RGB matrices not inverse");
    }

    #[test]
    fn test_rec2020_matrices_are_inverses() {
        let product = mat_mul(REC2020_TO_XYZ, XYZ_TO_REC2020);
        assert!(is_identity(product, 1e-10), "Rec.2020 matrices not inverse");
    }

    #[test]
    fn test_ycbcr_matrices_are_inverses() {
        let product = mat_mul(RGB_TO_YCBCR, YCBCR_TO_RGB);
        assert!(is_identity(product, 1e-10), "Y'CbCr matrices not inverse");
    }

    #[test]
    fn test_cielab_epsilon() {
        let expected = (6.0_f64 / 29.0).powi(3);
        assert!((cielab::EPSILON - expected).abs() < 1e-15);
    }

    #[test]
    fn test_cielab_kappa() {
        let expected = (29.0_f64 / 6.0).powi(2) / 3.0;
        assert!((cielab::KAPPA - expected).abs() < 1e-12);
    }

    #[test]
    fn test_srgb_white_matches_d65() {
        // RGB (1,1,1) maps to white XYZ via matrix row sums.
        // This should match D65 since sRGB matrices are derived from D65 (0.3127, 0.3290).
        let x = SRGB_TO_XYZ[0][0] + SRGB_TO_XYZ[0][1] + SRGB_TO_XYZ[0][2];
        let y = SRGB_TO_XYZ[1][0] + SRGB_TO_XYZ[1][1] + SRGB_TO_XYZ[1][2];
        let z = SRGB_TO_XYZ[2][0] + SRGB_TO_XYZ[2][1] + SRGB_TO_XYZ[2][2];
        assert!((x - d65::XYZ_X).abs() < 1e-14, "X: {} vs {}", x, d65::XYZ_X);
        assert!((y - d65::XYZ_Y).abs() < 1e-14, "Y: {} vs {}", y, d65::XYZ_Y);
        assert!((z - d65::XYZ_Z).abs() < 1e-14, "Z: {} vs {}", z, d65::XYZ_Z);
    }

    #[test]
    fn test_apple_direct_matrices_are_inverses() {
        let product = mat_mul(APPLE_RGB_TO_SRGB, SRGB_TO_APPLE_RGB);
        assert!(is_identity(product, 1e-10), "Apple RGB direct matrices not inverse");
    }

    #[test]
    fn test_p3_direct_matrices_are_inverses() {
        let product = mat_mul(DISPLAY_P3_TO_SRGB, SRGB_TO_DISPLAY_P3);
        assert!(is_identity(product, 1e-10), "Display P3 direct matrices not inverse");
    }

    #[test]
    fn test_adobe_direct_matrices_are_inverses() {
        let product = mat_mul(ADOBE_RGB_TO_SRGB, SRGB_TO_ADOBE_RGB);
        assert!(is_identity(product, 1e-10), "Adobe RGB direct matrices not inverse");
    }

    #[test]
    fn test_rec2020_direct_matrices_are_inverses() {
        let product = mat_mul(REC2020_TO_SRGB, SRGB_TO_REC2020);
        assert!(is_identity(product, 1e-10), "Rec.2020 direct matrices not inverse");
    }

    #[test]
    fn test_prophoto_direct_matrices_are_inverses() {
        let product = mat_mul(PROPHOTO_RGB_TO_SRGB, SRGB_TO_PROPHOTO_RGB);
        assert!(is_identity(product, 1e-10), "ProPhoto RGB direct matrices not inverse");
    }

    #[test]
    fn test_bradford_matrices_are_inverses() {
        let product = mat_mul(BRADFORD, BRADFORD_INV);
        assert!(is_identity(product, 1e-10), "Bradford matrices not inverse");
    }

    #[test]
    fn test_d50_d65_adaptation_roundtrip() {
        let product = mat_mul(ADAPT_D50_TO_D65, ADAPT_D65_TO_D50);
        assert!(is_identity(product, 1e-10), "D50<->D65 adaptation not inverse");
    }
}
